PREFIX edo-ifc: <https://w3id.org/energy-domain/edo/mappings/ifc#>

SELECT ?s ?p ?o
WHERE {
  BIND(<https://w3id.org/energy-domain/edo/mappings/ifc#-> AS ?placeholder)
  {
    ?s ?p ?placeholder .
    BIND(?placeholder AS ?o)
  }
  UNION
  {
    ?placeholder ?p ?o .
    BIND(?placeholder AS ?s)
  }
}
