PREFIX edo-ifc: <https://w3id.org/energy-domain/edo/mappings/ifc#>

SELECT ?edoConcept ?objectType
WHERE {
  ?edoConcept edo-ifc:ifc_objectType ?objectType .
  FILTER(REGEX(STR(?objectType), "^Ifc[A-Z]"))
}
ORDER BY ?edoConcept
