PREFIX edo-ifc: <https://w3id.org/energy-domain/edo/mappings/ifc#>

SELECT ?edoConcept ?ifcEntity ?objectType ?predefinedType ?relatingRole ?relatedRole
WHERE {
  ?edoConcept edo-ifc:ifc_equivalentClass ?ifcEntity .

  OPTIONAL { ?edoConcept edo-ifc:ifc_objectType ?objectType . }
  OPTIONAL { ?edoConcept edo-ifc:ifc_predefinedType ?predefinedType . }
  OPTIONAL { ?edoConcept edo-ifc:ifc_relatingRole ?relatingRole . }
  OPTIONAL { ?edoConcept edo-ifc:ifc_relatedRole ?relatedRole . }
}
ORDER BY ?edoConcept
