PREFIX edo: <https://w3id.org/energy-domain/edo#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?attribute
WHERE {
  ?attribute rdfs:subClassOf* edo:DomainAttribute .
  FILTER NOT EXISTS { ?attribute edo:attributeNature ?nature . }
}
ORDER BY ?attribute
